# Generated by Django 3.2.9 on 2021-11-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='uploaded',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='home',
            name='body',
        ),
    ]
