# Generated by Django 3.2.9 on 2021-11-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211127_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='uploaded',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='uploaded',
            new_name='updated',
        ),
    ]
