# Generated by Django 3.2.9 on 2021-11-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211128_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uploaded',
            new_name='updated',
        ),
    ]
