# Generated by Django 3.2.9 on 2021-11-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_uploaded_category_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated',
        ),
    ]
